import { WheelMenuItem } from '../types';

// Example game lists for each system
const nesGames = [
  { id: 'nes-1', name: 'Super Mario Bros.', romPath: '/roms/nes/smb.nes' },
  { id: 'nes-2', name: 'The Legend of Zelda', romPath: '/roms/nes/zelda.nes' },
  { id: 'nes-3', name: 'Metroid', romPath: '/roms/nes/metroid.nes' },
  { id: 'nes-4', name: 'Mega Man 2', romPath: '/roms/nes/megaman2.nes' },
  { id: 'nes-5', name: 'Castlevania', romPath: '/roms/nes/castlevania.nes' },
];

const snesGames = [
  { id: 'snes-1', name: 'Super Mario World', romPath: '/roms/snes/smw.smc' },
  { id: 'snes-2', name: 'A Link to the Past', romPath: '/roms/snes/alttp.smc' },
  { id: 'snes-3', name: 'Super Metroid', romPath: '/roms/snes/smetroid.smc' },
  { id: 'snes-4', name: 'Chrono Trigger', romPath: '/roms/snes/chrono.smc' },
];

const n64Games = [
  { id: 'n64-1', name: 'Super Mario 64', romPath: '/roms/n64/sm64.z64' },
  { id: 'n64-2', name: 'Ocarina of Time', romPath: '/roms/n64/oot.z64' },
  { id: 'n64-3', name: 'GoldenEye 007', romPath: '/roms/n64/goldeneye.z64' },
];

// Settings options
const settingsOptions = [
  { id: 'settings-display', name: 'Display Settings', action: 'display' },
  { id: 'settings-audio', name: 'Audio Settings', action: 'audio' },
  { id: 'settings-controls', name: 'Controller Settings', action: 'controls' },
  { id: 'settings-paths', name: 'ROM Paths', action: 'paths' },
  { id: 'settings-themes', name: 'Theme Selection', action: 'themes' },
  { id: 'settings-about', name: 'About', action: 'about' },
];

export const systems: WheelMenuItem[] = [
  {
    id: 'nes',
    label: 'NES',
    icon: '/logos/nes.png',
    color: '#E60012',
    description: 'Nintendo Entertainment System',
    year: '1983',
    games: nesGames,
  },
  {
    id: 'snes',
    label: 'SNES',
    icon: '/logos/snes.png',
    color: '#5C5CAB',
    description: 'Super Nintendo Entertainment System',
    year: '1990',
    games: snesGames,
  },
  {
    id: 'n64',
    label: 'N64',
    icon: '/logos/n64.png',
    color: '#0080C8',
    description: 'Nintendo 64',
    year: '1996',
    games: n64Games,
  },
  {
    id: 'gb',
    label: 'GB',
    icon: '/logos/gb.png',
    color: '#8BAC0F',
    description: 'Game Boy',
    year: '1989',
    games: [],
  },
  {
    id: 'gbc',
    label: 'GBC',
    icon: '/logos/gbc.png',
    color: '#9B30FF',
    description: 'Game Boy Color',
    year: '1998',
    games: [],
  },
  {
    id: 'gba',
    label: 'GBA',
    icon: '/logos/gba.png',
    color: '#4169E1',
    description: 'Game Boy Advance',
    year: '2001',
    games: [],
  },
  {
    id: 'nds',
    label: 'NDS',
    icon: '/logos/nds.png',
    color: '#D3D3D3',
    description: 'Nintendo DS',
    year: '2004',
    games: [],
  },
  {
    id: 'psx',
    label: 'PSX',
    icon: '/logos/psx.png',
    color: '#003087',
    description: 'PlayStation',
    year: '1994',
    games: [],
  },
  {
    id: 'ps2',
    label: 'PS2',
    icon: '/logos/ps2.png',
    color: '#000080',
    description: 'PlayStation 2',
    year: '2000',
    games: [],
  },
  {
    id: 'genesis',
    label: 'Genesis',
    icon: '/logos/genesis.png',
    color: '#000000',
    description: 'Sega Genesis',
    year: '1988',
    games: [],
  },
  {
    id: 'dreamcast',
    label: 'Dreamcast',
    icon: '/logos/dreamcast.png',
    color: '#FF6600',
    description: 'Sega Dreamcast',
    year: '1998',
    games: [],
  },
  {
    id: 'arcade',
    label: 'Arcade',
    icon: '/logos/arcade.png',
    color: '#FFD700',
    description: 'Arcade Games',
    year: 'Various',
    games: [],
  },
  {
    id: 'mame',
    label: 'MAME',
    icon: '/logos/mame.png',
    color: '#FF4500',
    description: 'Multiple Arcade Machine Emulator',
    year: 'Various',
    games: [],
  },
  {
    id: 'atari2600',
    label: 'Atari 2600',
    icon: '/logos/atari2600.png',
    color: '#D4AF37',
    description: 'Atari 2600',
    year: '1977',
    games: [],
  },
  {
    id: 'atarilynx',
    label: 'Atari Lynx',
    icon: '/logos/atarilynx.png',
    color: '#FF6347',
    description: 'Atari Lynx',
    year: '1989',
    games: [],
  },
  {
    id: 'gamegear',
    label: 'Game Gear',
    icon: '/logos/gamegear.png',
    color: '#1E90FF',
    description: 'Sega Game Gear',
    year: '1990',
    games: [],
  },
  {
    id: 'mastersystem',
    label: 'Master System',
    icon: '/logos/mastersystem.png',
    color: '#DC143C',
    description: 'Sega Master System',
    year: '1985',
    games: [],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: '/logos/settings.png',
    color: '#808080',
    description: 'Emulator Settings',
    year: '',
    games: settingsOptions,
  },
];
